language: smalltalk
sudo: false
os:
- linux
smalltalk:
- Pharo64-7.0
- Pharo-7.0
- Pharo-6.1
- Pharo-5.0
matrix:
  allow_failures:
  - smalltalk: Pharo64-7.0
  - smalltalk: Pharo-7.0
  fast_finish: true
before_deploy:
  - cp "${SMALLTALK_CI_IMAGE}" "Willow-SemanticUI.image"
  - cp "${SMALLTALK_CI_CHANGES}" "Willow-SemanticUI.changes"
  - zip -q "${TRAVIS_BRANCH}-${TRAVIS_SMALLTALK_VERSION}.zip" "Willow-SemanticUI.image" "Willow-SemanticUI.changes"
deploy:
  provider: releases
  api_key:
    secure: ljuW9P8QVrgxBuNFNBie3Xp8+F3NZiOA5JgEilSHQAJ/UzzQ/i5sjCzED53L5isaTdKAk86WB/JKl/rstQnILPrSrGg6O49JcqqlP+B/fLsrJlitFXAlNxTbG8MJE7wftBBOzothnu7UfKFHWCMI36v0lUdWqiy42nChh+sGSYG/niCC/TdnJfPVXQJVHdNlTLPKUERsBae4GOYgMQ7fIpYLFR5H1cCJoWDHoUQoxvaENbGTh5uBOV+223PlWBVJeo5cGIWKpFVETr9HpO1/ewmqkh3ZSb5zQXJ7grEj6SfHWK/Rv5ngY7GJavPt99SkWcg+VhtoRLMEGmJ2DTsh7AE2LXoxG+o16unT7KH6iw84HOihKCz1NsCJ6K8zJPHL1ZwfsSx6QJh9NdMSEpjOU78od520qxcw5kWMjLVQE4gg8qk+cN9KfPxtVpeKn08TMD5nHS8v9zQiVmNPx761Jj3dKxqiBh6hOsS3Vc/SmgH/vp2P5AatO9bgaJqgw5f8CRMlRdFNP6e4FqunFpGVBCc9//+FNcKHgPhIKph6msic+BNVqfi+1vtf/T48rVVe49q7YHZvUgcb3/fWB4FyT5+pfGxWku3DhTXW1sVHPa34KfTT5MJzBybIcTa0A2BJZH3g07kcwyNftdVcC/W1XdFEetUoLA0w/npTh3XeT/g=
  file: "${TRAVIS_BRANCH}-${TRAVIS_SMALLTALK_VERSION}.zip"
  skip_cleanup: true
  on:
    repo: ba-st/Willow-SemanticUI
    tags: true
